### ISSUE TITLE
[BUG] Enter bug description

### ISSUE THREAD

**Issue by ndwzl** [GreaterWMS/GreaterWMS#219]
2022-07-10 23:29:20,415 ERROR    Internal Server Error: /asn/detail/
Traceback (most recent call last):
  File "d:\program files\python39\lib\site-packages\asgiref\sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "d:\program files\python39\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "d:\program files\python39\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "d:\program files\python39\lib\site-packages\asgiref\sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "d:\program files\python39\lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
  File "d:\program files\python39\lib\site-packages\asgiref\current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\program files\python39\lib\site-packages\asgiref\sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "d:\program files\python39\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "d:\program files\python39\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "d:\program files\python39\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "d:\program files\python39\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "d:\program files\python39\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "d:\program files\python39\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\develop\work\GreaterWMS-master\.\asn\views.py", line 244, in create
    warehouse_city = warehouse.objects.filter(openid=self.request.auth.openid).first().warehouse_city
AttributeError: 'NoneType' object has no attribute 'warehouse_city'
127.0.0.1:59117 - - [10/Jul/2022:23:29:20] "POST /asn/detail/" 500 145
127.0.0.1:59117 - - [10/Jul/2022:23:29:38] "GET /stock/list/?ordering=-update_time" 200 3214

**Comment by Singosgu** [comment]
you should set up your warehouse baseinfo
