### ISSUE TITLE
当项目启动的时候出现找不到该模块，但是我利用全局搜索还是找不到该模块

### ISSUE THREAD

**Issue by Hellathor** [GreaterWMS/GreaterWMS#225]
"C:\Software\PyCharm 2020.2.3\bin\runnerw64.exe" C:\project\VMS\venv-wms\Scripts\python.exe C:/project/VMS/GreaterWMS/manage.py runserver 8000
Traceback (most recent call last):
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\commands\runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\software\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'GreaterWMS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\project\VMS\GreaterWMS\manage.py", line 22, in <module>
    main()
  File "C:\project\VMS\GreaterWMS\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\core\management\base.py", line 343, in run_from_argv
    connections.close_all()
  File "C:\project\VMS\venv-wms\lib\site-packages\django\db\utils.py", line 232, in close_all
    for alias in self:
  File "C:\project\VMS\venv-wms\lib\site-packages\django\db\utils.py", line 226, in __iter__
    return iter(self.databases)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\db\utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\project\VMS\venv-wms\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\software\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'GreaterWMS'

Process finished with exit code 1

**Comment by Singosgu** [comment]
daphne -b 0.0.0.0 -p 8008 greaterwms.asgi:application
