### ISSUE TITLE
注册时提示Resource does not exist(404)

### ISSUE THREAD

**Issue by belth0219** [GreaterWMS/GreaterWMS#263]
网页报错 Resource does not exist(404)
后台提示
[django.request.log_response() :241] [WARMING] Not Found: //register/
 "POST //register/" 404 6501
请问这是什么问题？

**Comment by Singosgu** [comment]
请求地址多了个/

**Comment by belth0219** [comment]
Traceback (most recent call last):
  File "/home/wms/miniconda3/envs/wms/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/wms/miniconda3/envs/wms/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: attempt to write a readonly database
这个怎么处理？

**Comment by belth0219** [comment]
谢谢
