### ISSUE TITLE
[BUG] docker部署的时候报错

### ISSUE THREAD

**Issue by Biely** [GreaterWMS/GreaterWMS#370]
ERROR: for backend  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper

**Comment by Singosgu** [comment]
为啥docker会调用py
